"""Whisper fallback utilities for transcript processing.

The service layer prefers platform captions first because that is lower latency
and lower cost. This module is deliberately isolated because speech-to-text often
needs heavier optional dependencies, temporary media files, and provider-specific
configuration.
"""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional
from uuid import uuid4

from .schema import (
    TranscriptProcessingConfig,
    TranscriptSegment,
    TranscriptSource,
    WhisperTranscriptionError,
)

logger = logging.getLogger(__name__)


class WhisperTranscriber:
    """Transcribe video/audio URLs with Whisper and return timestamped segments.

    The implementation supports local OpenAI Whisper when the optional ``whisper``
    package is installed. It also uses ``yt-dlp`` to download audio from public
    video URLs. Both dependencies are imported lazily so the rest of the backend
    can run tests without installing media/transcription packages.
    """

    def __init__(self, config: Optional[TranscriptProcessingConfig] = None) -> None:
        self.config = config or TranscriptProcessingConfig()

    def transcribe_url(self, source_url: str, *, language: Optional[str] = None) -> List[TranscriptSegment]:
        """Download audio for ``source_url`` and transcribe it with Whisper.

        Args:
            source_url: YouTube/Instagram/public video URL to download audio from.
            language: Optional language hint. Defaults to config language.

        Returns:
            Timestamped transcript segments generated by Whisper.

        Raises:
            WhisperTranscriptionError: If media download or transcription fails.
        """
        audio_path: Optional[Path] = None
        try:
            audio_path = self._download_audio(source_url)
            return self.transcribe_file(audio_path, language=language or self.config.language)
        finally:
            if audio_path is not None:
                try:
                    audio_path.unlink(missing_ok=True)
                except OSError:
                    # Temporary-file cleanup should never mask the real extraction result.
                    logger.warning("Failed to remove temporary audio file: %s", audio_path, exc_info=True)

    def transcribe_file(self, audio_path: Path | str, *, language: Optional[str] = None) -> List[TranscriptSegment]:
        """Transcribe an already-downloaded audio/video file.

        The returned segment objects preserve start/end timestamps so downstream
        retrieval can cite exact moments in the video.
        """
        path = Path(audio_path)
        if not path.exists():
            raise WhisperTranscriptionError(f"Audio file does not exist: {path}")

        try:
            import whisper  # type: ignore[import-not-found]
        except Exception as exc:  # pragma: no cover - depends on optional package
            raise WhisperTranscriptionError(
                "Whisper fallback requires the optional 'whisper' package. "
                "Install openai-whisper or disable Whisper fallback."
            ) from exc

        try:
            logger.info("Loading Whisper model '%s'", self.config.whisper_model)
            model = whisper.load_model(self.config.whisper_model)
            logger.info("Running Whisper transcription for %s", path)
            result: Dict[str, Any] = model.transcribe(str(path), language=language)
        except Exception as exc:  # pragma: no cover - model/runtime dependent
            raise WhisperTranscriptionError(f"Whisper transcription failed: {exc}") from exc

        segments = result.get("segments") or []
        normalized: List[TranscriptSegment] = []
        for index, item in enumerate(segments):
            text = str(item.get("text") or "").strip()
            if not text:
                continue
            normalized.append(
                TranscriptSegment(
                    segment_index=index,
                    text=text,
                    start_seconds=float(item.get("start") or 0.0),
                    end_seconds=float(item.get("end") or item.get("start") or 0.0),
                    source_type=TranscriptSource.WHISPER,
                    confidence=None,
                    raw=item,
                )
            )

        if not normalized:
            raise WhisperTranscriptionError("Whisper returned no usable transcript segments.")

        logger.info("Whisper generated %d transcript segments", len(normalized))
        return normalized

    def _download_audio(self, source_url: str) -> Path:
        """Download best-effort audio using yt-dlp and return a local file path."""
        try:
            import yt_dlp  # type: ignore[import-not-found]
        except Exception as exc:  # pragma: no cover - depends on optional package
            raise WhisperTranscriptionError(
                "Whisper fallback requires 'yt-dlp' to download audio. Install yt-dlp or disable fallback."
            ) from exc

        temp_root = Path(self.config.temp_dir)
        temp_root.mkdir(parents=True, exist_ok=True)
        output_template = str(temp_root / f"{uuid4().hex}.%(ext)s")

        ydl_opts: Dict[str, Any] = {
            "format": "bestaudio/best",
            "outtmpl": output_template,
            "quiet": True,
            "noplaylist": True,
            "max_filesize": 100 * 1024 * 1024,  # Guardrail for demo/MVP usage.
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": "mp3",
                    "preferredquality": "96",
                }
            ],
        }

        try:
            logger.info("Downloading audio for Whisper fallback")
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(source_url, download=True)
                downloaded = Path(ydl.prepare_filename(info)).with_suffix(".mp3")
        except Exception as exc:  # pragma: no cover - network/platform dependent
            raise WhisperTranscriptionError(f"Audio download failed: {exc}") from exc

        if not downloaded.exists():
            # Some postprocessor paths differ by source extension. Search only the
            # temp directory for a matching UUID prefix to avoid unsafe globbing.
            candidates = sorted(temp_root.glob(Path(output_template).name.replace("%(ext)s", "*")))
            downloaded = candidates[0] if candidates else downloaded

        if not downloaded.exists():
            raise WhisperTranscriptionError("yt-dlp completed but no audio file was produced.")

        return downloaded
