"""Qdrant adapter for transcript vectors.

The rest of the application should not import qdrant-client models directly.
This adapter owns collection creation, payload index setup, upserts, and filtered
similarity search. That separation keeps the service layer focused on product
workflow instead of database protocol details.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable, Sequence
from typing import Any

from qdrant_client import AsyncQdrantClient
from qdrant_client.http import models as qm

from .schema import ChunkMetadata, IndexedVector, TranscriptChunkInput, VectorSearchResult, VectorStoreSettings

logger = logging.getLogger(__name__)


class QdrantVectorStoreError(RuntimeError):
    """Raised when Qdrant operations fail in a way callers should handle."""


class QdrantTranscriptStore:
    """Small, production-shaped Qdrant wrapper for transcript chunk vectors."""

    def __init__(self, settings: VectorStoreSettings) -> None:
        self.settings = settings
        self.collection_name = settings.qdrant_collection
        self.client = AsyncQdrantClient(
            url=settings.qdrant_url,
            api_key=settings.qdrant_api_key,
            timeout=settings.qdrant_timeout_seconds,
        )

    async def ensure_collection(self) -> None:
        """Create the collection and payload indexes if they do not exist.

        This method is safe to call at application startup and before indexing.
        It deliberately does not delete/recreate existing collections because that
        would wipe user data in production. If vector size changes, run a managed
        migration instead.
        """

        try:
            exists = await self.client.collection_exists(self.collection_name)
            if not exists:
                logger.info("Creating Qdrant collection %s", self.collection_name)
                await self.client.create_collection(
                    collection_name=self.collection_name,
                    vectors_config=qm.VectorParams(
                        size=self.settings.qdrant_vector_size,
                        distance=qm.Distance.COSINE,
                    ),
                )
            await self._ensure_payload_indexes()
        except Exception as exc:  # pragma: no cover - exact client exceptions vary by transport
            raise QdrantVectorStoreError(f"Failed to ensure Qdrant collection: {exc}") from exc

    async def _ensure_payload_indexes(self) -> None:
        """Create indexes used by the retrieval filters.

        Index creation is idempotent from the app's perspective. Some Qdrant
        versions raise if the index already exists, so known duplicate-index
        failures are logged and ignored.
        """

        index_specs: dict[str, qm.PayloadSchemaType] = {
            "comparison_id": qm.PayloadSchemaType.KEYWORD,
            "video_id": qm.PayloadSchemaType.KEYWORD,
            "platform": qm.PayloadSchemaType.KEYWORD,
            "chunk_index": qm.PayloadSchemaType.INTEGER,
        }

        for field_name, schema in index_specs.items():
            try:
                await self.client.create_payload_index(
                    collection_name=self.collection_name,
                    field_name=field_name,
                    field_schema=schema,
                )
            except Exception as exc:  # pragma: no cover - wording differs across Qdrant versions
                message = str(exc).lower()
                if "already exists" in message or "conflict" in message:
                    logger.debug("Qdrant payload index already exists: %s", field_name)
                    continue
                raise

    async def upsert_chunks(
        self,
        *,
        chunks: Sequence[TranscriptChunkInput],
        vectors: Sequence[Sequence[float]],
        point_ids: Sequence[str],
        embedding_model: str,
    ) -> list[IndexedVector]:
        """Upsert transcript chunks and vectors into Qdrant.

        Upsert semantics are essential here: re-running the indexing job for the
        same chunk should overwrite the old point instead of duplicating it.
        Deterministic point IDs are generated by the service layer.
        """

        if len(chunks) != len(vectors) or len(chunks) != len(point_ids):
            raise ValueError("chunks, vectors, and point_ids must have the same length")

        await self.ensure_collection()

        indexed: list[IndexedVector] = []
        for start in range(0, len(chunks), self.settings.qdrant_write_batch_size):
            batch_chunks = chunks[start : start + self.settings.qdrant_write_batch_size]
            batch_vectors = vectors[start : start + self.settings.qdrant_write_batch_size]
            batch_ids = point_ids[start : start + self.settings.qdrant_write_batch_size]

            points = [
                qm.PointStruct(
                    id=point_id,
                    vector=list(vector),
                    payload=chunk.metadata.to_payload(chunk.text, embedding_model),
                )
                for point_id, vector, chunk in zip(batch_ids, batch_vectors, batch_chunks, strict=True)
            ]

            try:
                await self.client.upsert(
                    collection_name=self.collection_name,
                    points=points,
                    wait=True,
                )
            except Exception as exc:  # pragma: no cover
                raise QdrantVectorStoreError(f"Failed to upsert vectors: {exc}") from exc

            indexed.extend(
                IndexedVector(
                    point_id=point_id,
                    comparison_id=chunk.metadata.comparison_id,
                    video_id=chunk.metadata.video_id,
                    chunk_id=chunk.metadata.chunk_id,
                    chunk_index=chunk.metadata.chunk_index,
                )
                for point_id, chunk in zip(batch_ids, batch_chunks, strict=True)
            )

        return indexed

    async def search(
        self,
        *,
        query_vector: Sequence[float],
        comparison_id: str,
        video_id: str | None = None,
        top_k: int = 8,
        score_threshold: float | None = None,
    ) -> list[VectorSearchResult]:
        """Run a session-scoped vector search.

        The comparison filter is mandatory because transcript chunks from other
        sessions must never be retrieved into this user's answer context.
        """

        await self.ensure_collection()
        qdrant_filter = self._build_filter(comparison_id=comparison_id, video_id=video_id)

        try:
            response = await self.client.query_points(
                collection_name=self.collection_name,
                query=list(query_vector),
                query_filter=qdrant_filter,
                limit=top_k,
                score_threshold=score_threshold,
                with_payload=True,
                with_vectors=False,
            )
        except Exception as exc:  # pragma: no cover
            raise QdrantVectorStoreError(f"Failed to search vectors: {exc}") from exc

        # Newer qdrant-client returns QueryResponse.points. Older versions may
        # return a list-like shape from search APIs; normalize defensively.
        raw_points = getattr(response, "points", response)
        return [self._to_search_result(point) for point in raw_points]

    def _build_filter(self, *, comparison_id: str, video_id: str | None = None) -> qm.Filter:
        must_conditions: list[qm.Condition] = [
            qm.FieldCondition(key="comparison_id", match=qm.MatchValue(value=comparison_id))
        ]
        if video_id:
            must_conditions.append(qm.FieldCondition(key="video_id", match=qm.MatchValue(value=video_id)))
        return qm.Filter(must=must_conditions)

    def _to_search_result(self, point: Any) -> VectorSearchResult:
        payload = dict(point.payload or {})
        text = str(payload.pop("text", ""))

        # Keep only fields known by ChunkMetadata plus any future extension fields
        # because ChunkMetadata allows extra="allow".
        metadata = ChunkMetadata.model_validate(payload)
        return VectorSearchResult(
            point_id=str(point.id),
            score=float(point.score),
            text=text,
            metadata=metadata,
        )

    async def delete_comparison(self, comparison_id: str) -> None:
        """Delete all chunks for a comparison.

        Useful for GDPR-style deletion, test cleanup, and failed-session resets.
        """

        await self.ensure_collection()
        try:
            await self.client.delete(
                collection_name=self.collection_name,
                points_selector=qm.FilterSelector(filter=self._build_filter(comparison_id=comparison_id)),
                wait=True,
            )
        except Exception as exc:  # pragma: no cover
            raise QdrantVectorStoreError(f"Failed to delete comparison vectors: {exc}") from exc

    async def close(self) -> None:
        """Close the underlying HTTP client when the app shuts down."""

        await self.client.close()
